spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
test:
  service: test_service